### PR TITLE
Update log to 0.4 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by rtbo** [comment]
Doesn't servo depend on version 0.7 of rust-xcb? servo team asked me to branch rust-xcb so they can keep depending on 0.7. Or that's what I understood.
see here #40

**Comment by Eijebong** [comment]
You're right, going to try updating it to 0.8, the issue should be fixed (the rust bug has been closed) ;)

**Comment by Eijebong** [comment]
Servo now depends on xcb 0.8 :tada:

**Comment by rtbo** [comment]
published on crates.io.
Thanks!

**Pull request merged**
